### ISSUE TITLE
The comments added in xlsx leads to zlib.error "Error -3 while decompressing: invalid stored block lengths"

### ISSUE THREAD

**Issue by YaroslavVarkholVS** [ktr/sxl#11]
![image](https://user-images.githubusercontent.com/42055981/93309694-7c7bb700-f80c-11ea-927b-1fbcb5041120.png)

**Comment by ktr** [comment]
Hi - thank you for the note. Are you able to provide a sample file? I just added another test for a new file with comments, and didn't run into any errors. If you can send me a sample, I will try with that Excel file and see what I can find.

**Comment by YaroslavVarkholVS** [comment]
Maybe the issue is not in comments, here are two sample files, the second one doesn't have comments:
[ErrorCausingTemplate.xlsx](https://github.com/ktr/sxl/files/5310366/ErrorCausingTemplate.xlsx)
[ErrorCausingTemplate_2.xlsx](https://github.com/ktr/sxl/files/5310367/ErrorCausingTemplate_2.xlsx)

Thank you.

**Comment by ktr** [comment]
Hi - sorry for delay. Can you let me know what version of Python you are using and also copy a screenshot of the  error you are getting? Also, what version of sxl have you downloaded?

You can get the version of sxl with:
`python -c "import sxl; print(sxl.__version__)"`

You can get the version of Python with:
`python --version`

I cannot reproduce the error you got (I just added the file you sent to the test suite without error). I added both, but since neither returned an error I just kept one in the repository.

Sorry I cannot help so far!

**Comment by YaroslavVarkholVS** [comment]
I assume the problem is in the `python 2.7.5` version and it should be `python 3`, sorry for bringing up this issue.

**Comment by ktr** [comment]
Sorry I did not respond. I had been meaning to try to get it working for Python 2, but have not had the time! If I do, I will let you know. Thank you.

**Comment by jkyeung** [comment]
Honestly, now is not the time to be *adding* Python 2 support.

**Comment by YaroslavVarkholVS** [comment]
Yes, that is right, Python 2 is going to become a history soon anyhow.
