### ISSUE TITLE
changing column names 

### ISSUE THREAD

**Issue by isiktopcu** [ktr/sxl#14]
Hi! Is it possible to change the column names without loading the whole excel file into the memory with this package?

**Comment by ktr** [comment]
Hi - do you mean to change a value and save it back to the Excel file? If
so, no - this package is focused on reading files rather than writing them.
If you mean change the column name as you are streaming the output, you
could - would just need a little more insight on what you’re trying to do
(e.g., maybe a code sample). Thanks.
